<?php

namespace Database\Seeders;

use App\Models\Part;
use Illuminate\Database\Seeder;

class PartSeeder extends Seeder
{
    public function run(): void
    {
        $parts = [
            [
                'part_number' => 'DEMO-0001',
                'name' => 'Engine Oil 5W30 1L',
                'category' => 'Engine',
                'brand' => 'Bosch',
                'unit' => 'bottle',
                'cost_price' => 250,
                'selling_price' => 380,
                'current_stock' => 8,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0002',
                'name' => 'Engine Oil 5W40 1L',
                'category' => 'Engine',
                'brand' => 'MANN',
                'unit' => 'bottle',
                'cost_price' => 250,
                'selling_price' => 380,
                'current_stock' => 11,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0003',
                'name' => 'Engine Oil 10W40 1L',
                'category' => 'Engine',
                'brand' => 'Valeo',
                'unit' => 'bottle',
                'cost_price' => 250,
                'selling_price' => 380,
                'current_stock' => 14,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0004',
                'name' => 'Oil Filter',
                'category' => 'Engine',
                'brand' => 'Denso',
                'unit' => 'bottle',
                'cost_price' => 250,
                'selling_price' => 380,
                'current_stock' => 17,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0005',
                'name' => 'Air Filter',
                'category' => 'Engine',
                'brand' => 'SKF',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 20,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0006',
                'name' => 'Fuel Filter',
                'category' => 'Engine',
                'brand' => 'NGK',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 23,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0007',
                'name' => 'Spark Plug',
                'category' => 'Engine',
                'brand' => 'Exide',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 26,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0008',
                'name' => 'Glow Plug',
                'category' => 'Engine',
                'brand' => 'Amaron',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 29,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0009',
                'name' => 'Engine Air Intake Hose',
                'category' => 'Engine',
                'brand' => 'Gates',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 6,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0010',
                'name' => 'PCV Valve',
                'category' => 'Engine',
                'brand' => 'Generic',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 9,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0011',
                'name' => 'Timing Belt Kit',
                'category' => 'Engine',
                'brand' => 'Bosch',
                'unit' => 'set',
                'cost_price' => 450,
                'selling_price' => 650,
                'current_stock' => 12,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0012',
                'name' => 'Serpentine Belt',
                'category' => 'Engine',
                'brand' => 'MANN',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 15,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0013',
                'name' => 'Tensioner Pulley',
                'category' => 'Engine',
                'brand' => 'Valeo',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 18,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0014',
                'name' => 'Engine Mount',
                'category' => 'Engine',
                'brand' => 'Denso',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 21,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0015',
                'name' => 'Rocker Cover Gasket',
                'category' => 'Engine',
                'brand' => 'SKF',
                'unit' => 'bottle',
                'cost_price' => 250,
                'selling_price' => 380,
                'current_stock' => 24,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0016',
                'name' => 'Cylinder Head Gasket',
                'category' => 'Engine',
                'brand' => 'NGK',
                'unit' => 'bottle',
                'cost_price' => 250,
                'selling_price' => 380,
                'current_stock' => 27,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0017',
                'name' => 'Oil Sump Gasket',
                'category' => 'Engine',
                'brand' => 'Exide',
                'unit' => 'bottle',
                'cost_price' => 250,
                'selling_price' => 380,
                'current_stock' => 30,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0018',
                'name' => 'Thermostat',
                'category' => 'Engine',
                'brand' => 'Amaron',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 7,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0019',
                'name' => 'Water Pump',
                'category' => 'Engine',
                'brand' => 'Gates',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 10,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0020',
                'name' => 'Radiator Cap',
                'category' => 'Engine',
                'brand' => 'Generic',
                'unit' => 'pcs',
                'cost_price' => 1800,
                'selling_price' => 2600,
                'current_stock' => 13,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0021',
                'name' => 'Coolant 1L',
                'category' => 'Fluids & Lubricants',
                'brand' => 'Bosch',
                'unit' => 'bottle',
                'cost_price' => 250,
                'selling_price' => 380,
                'current_stock' => 16,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0022',
                'name' => 'Brake Fluid DOT 4 500ml',
                'category' => 'Fluids & Lubricants',
                'brand' => 'MANN',
                'unit' => 'bottle',
                'cost_price' => 250,
                'selling_price' => 380,
                'current_stock' => 19,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0023',
                'name' => 'Power Steering Fluid 1L',
                'category' => 'Fluids & Lubricants',
                'brand' => 'Valeo',
                'unit' => 'bottle',
                'cost_price' => 250,
                'selling_price' => 380,
                'current_stock' => 22,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0024',
                'name' => 'Gear Oil 1L',
                'category' => 'Fluids & Lubricants',
                'brand' => 'Denso',
                'unit' => 'bottle',
                'cost_price' => 250,
                'selling_price' => 380,
                'current_stock' => 25,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0025',
                'name' => 'ATF Fluid 1L',
                'category' => 'Fluids & Lubricants',
                'brand' => 'SKF',
                'unit' => 'bottle',
                'cost_price' => 250,
                'selling_price' => 380,
                'current_stock' => 28,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0026',
                'name' => 'Windshield Washer Fluid 1L',
                'category' => 'Fluids & Lubricants',
                'brand' => 'NGK',
                'unit' => 'bottle',
                'cost_price' => 250,
                'selling_price' => 380,
                'current_stock' => 5,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0027',
                'name' => 'Grease 500g',
                'category' => 'Fluids & Lubricants',
                'brand' => 'Exide',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 8,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0028',
                'name' => 'Chain Lubricant',
                'category' => 'Fluids & Lubricants',
                'brand' => 'Amaron',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 11,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0029',
                'name' => 'AC Compressor Oil',
                'category' => 'Fluids & Lubricants',
                'brand' => 'Gates',
                'unit' => 'pcs',
                'cost_price' => 1800,
                'selling_price' => 2600,
                'current_stock' => 14,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0030',
                'name' => 'Injector Cleaner',
                'category' => 'Fluids & Lubricants',
                'brand' => 'Generic',
                'unit' => 'bottle',
                'cost_price' => 250,
                'selling_price' => 380,
                'current_stock' => 17,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0031',
                'name' => 'Front Brake Pad Set',
                'category' => 'Brakes',
                'brand' => 'Bosch',
                'unit' => 'set',
                'cost_price' => 450,
                'selling_price' => 650,
                'current_stock' => 20,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0032',
                'name' => 'Rear Brake Pad Set',
                'category' => 'Brakes',
                'brand' => 'MANN',
                'unit' => 'set',
                'cost_price' => 450,
                'selling_price' => 650,
                'current_stock' => 23,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0033',
                'name' => 'Brake Shoe Set',
                'category' => 'Brakes',
                'brand' => 'Valeo',
                'unit' => 'set',
                'cost_price' => 450,
                'selling_price' => 650,
                'current_stock' => 26,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0034',
                'name' => 'Brake Disc Front',
                'category' => 'Brakes',
                'brand' => 'Denso',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 29,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0035',
                'name' => 'Brake Disc Rear',
                'category' => 'Brakes',
                'brand' => 'SKF',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 6,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0036',
                'name' => 'Brake Drum',
                'category' => 'Brakes',
                'brand' => 'NGK',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 9,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0037',
                'name' => 'Brake Caliper Repair Kit',
                'category' => 'Brakes',
                'brand' => 'Exide',
                'unit' => 'set',
                'cost_price' => 450,
                'selling_price' => 650,
                'current_stock' => 12,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0038',
                'name' => 'Brake Hose',
                'category' => 'Brakes',
                'brand' => 'Amaron',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 15,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0039',
                'name' => 'Brake Master Cylinder',
                'category' => 'Brakes',
                'brand' => 'Gates',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 18,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0040',
                'name' => 'Wheel Cylinder',
                'category' => 'Brakes',
                'brand' => 'Generic',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 21,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0041',
                'name' => 'Brake Cleaner Spray',
                'category' => 'Brakes',
                'brand' => 'Bosch',
                'unit' => 'bottle',
                'cost_price' => 250,
                'selling_price' => 380,
                'current_stock' => 24,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0042',
                'name' => 'ABS Sensor Front',
                'category' => 'Brakes',
                'brand' => 'MANN',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 27,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0043',
                'name' => 'ABS Sensor Rear',
                'category' => 'Brakes',
                'brand' => 'Valeo',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 30,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0044',
                'name' => 'Front Shock Absorber',
                'category' => 'Suspension & Steering',
                'brand' => 'Denso',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 7,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0045',
                'name' => 'Rear Shock Absorber',
                'category' => 'Suspension & Steering',
                'brand' => 'SKF',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 10,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0046',
                'name' => 'Strut Mount',
                'category' => 'Suspension & Steering',
                'brand' => 'NGK',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 13,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0047',
                'name' => 'Lower Arm Assembly',
                'category' => 'Suspension & Steering',
                'brand' => 'Exide',
                'unit' => 'pcs',
                'cost_price' => 1800,
                'selling_price' => 2600,
                'current_stock' => 16,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0048',
                'name' => 'Lower Arm Bush',
                'category' => 'Suspension & Steering',
                'brand' => 'Amaron',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 19,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0049',
                'name' => 'Stabilizer Link',
                'category' => 'Suspension & Steering',
                'brand' => 'Gates',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 22,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0050',
                'name' => 'Stabilizer Bush',
                'category' => 'Suspension & Steering',
                'brand' => 'Generic',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 25,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0051',
                'name' => 'Ball Joint',
                'category' => 'Suspension & Steering',
                'brand' => 'Bosch',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 28,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0052',
                'name' => 'Tie Rod End',
                'category' => 'Suspension & Steering',
                'brand' => 'MANN',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 5,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0053',
                'name' => 'Rack End',
                'category' => 'Suspension & Steering',
                'brand' => 'Valeo',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 8,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0054',
                'name' => 'Steering Rack Boot',
                'category' => 'Suspension & Steering',
                'brand' => 'Denso',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 11,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0055',
                'name' => 'Wheel Bearing Front',
                'category' => 'Suspension & Steering',
                'brand' => 'SKF',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 14,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0056',
                'name' => 'Wheel Bearing Rear',
                'category' => 'Suspension & Steering',
                'brand' => 'NGK',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 17,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0057',
                'name' => 'Coil Spring',
                'category' => 'Suspension & Steering',
                'brand' => 'Exide',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 20,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0058',
                'name' => 'Suspension Bush Kit',
                'category' => 'Suspension & Steering',
                'brand' => 'Amaron',
                'unit' => 'set',
                'cost_price' => 450,
                'selling_price' => 650,
                'current_stock' => 23,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0059',
                'name' => 'Clutch Plate',
                'category' => 'Clutch & Transmission',
                'brand' => 'Gates',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 26,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0060',
                'name' => 'Clutch Cover',
                'category' => 'Clutch & Transmission',
                'brand' => 'Generic',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 29,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0061',
                'name' => 'Clutch Release Bearing',
                'category' => 'Clutch & Transmission',
                'brand' => 'Bosch',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 6,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0062',
                'name' => 'Clutch Master Cylinder',
                'category' => 'Clutch & Transmission',
                'brand' => 'MANN',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 9,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0063',
                'name' => 'Clutch Slave Cylinder',
                'category' => 'Clutch & Transmission',
                'brand' => 'Valeo',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 12,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0064',
                'name' => 'Gearbox Mount',
                'category' => 'Clutch & Transmission',
                'brand' => 'Denso',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 15,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0065',
                'name' => 'CV Joint Outer',
                'category' => 'Clutch & Transmission',
                'brand' => 'SKF',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 18,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0066',
                'name' => 'CV Joint Inner',
                'category' => 'Clutch & Transmission',
                'brand' => 'NGK',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 21,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0067',
                'name' => 'CV Boot Kit',
                'category' => 'Clutch & Transmission',
                'brand' => 'Exide',
                'unit' => 'set',
                'cost_price' => 450,
                'selling_price' => 650,
                'current_stock' => 24,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0068',
                'name' => 'Drive Shaft Assembly',
                'category' => 'Clutch & Transmission',
                'brand' => 'Amaron',
                'unit' => 'pcs',
                'cost_price' => 1800,
                'selling_price' => 2600,
                'current_stock' => 27,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0069',
                'name' => 'Transmission Oil Seal',
                'category' => 'Clutch & Transmission',
                'brand' => 'Gates',
                'unit' => 'bottle',
                'cost_price' => 250,
                'selling_price' => 380,
                'current_stock' => 30,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0070',
                'name' => 'Clutch Cable',
                'category' => 'Clutch & Transmission',
                'brand' => 'Generic',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 7,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0071',
                'name' => 'Radiator Assembly',
                'category' => 'Cooling System',
                'brand' => 'Bosch',
                'unit' => 'pcs',
                'cost_price' => 1800,
                'selling_price' => 2600,
                'current_stock' => 10,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0072',
                'name' => 'Radiator Hose Upper',
                'category' => 'Cooling System',
                'brand' => 'MANN',
                'unit' => 'pcs',
                'cost_price' => 1800,
                'selling_price' => 2600,
                'current_stock' => 13,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0073',
                'name' => 'Radiator Hose Lower',
                'category' => 'Cooling System',
                'brand' => 'Valeo',
                'unit' => 'pcs',
                'cost_price' => 1800,
                'selling_price' => 2600,
                'current_stock' => 16,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0074',
                'name' => 'Radiator Fan Motor',
                'category' => 'Cooling System',
                'brand' => 'Denso',
                'unit' => 'pcs',
                'cost_price' => 1800,
                'selling_price' => 2600,
                'current_stock' => 19,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0075',
                'name' => 'Radiator Fan Relay',
                'category' => 'Cooling System',
                'brand' => 'SKF',
                'unit' => 'pcs',
                'cost_price' => 1800,
                'selling_price' => 2600,
                'current_stock' => 22,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0076',
                'name' => 'Expansion Tank',
                'category' => 'Cooling System',
                'brand' => 'NGK',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 25,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0077',
                'name' => 'Expansion Tank Cap',
                'category' => 'Cooling System',
                'brand' => 'Exide',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 28,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0078',
                'name' => 'Coolant Temperature Sensor',
                'category' => 'Cooling System',
                'brand' => 'Amaron',
                'unit' => 'bottle',
                'cost_price' => 250,
                'selling_price' => 380,
                'current_stock' => 5,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0079',
                'name' => 'Radiator Flush Chemical',
                'category' => 'Cooling System',
                'brand' => 'Gates',
                'unit' => 'pcs',
                'cost_price' => 1800,
                'selling_price' => 2600,
                'current_stock' => 8,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0080',
                'name' => 'Water Pipe O-Ring',
                'category' => 'Cooling System',
                'brand' => 'Generic',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 11,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0081',
                'name' => 'AC Cabin Filter',
                'category' => 'AC & HVAC',
                'brand' => 'Bosch',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 14,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0082',
                'name' => 'AC Compressor',
                'category' => 'AC & HVAC',
                'brand' => 'MANN',
                'unit' => 'pcs',
                'cost_price' => 1800,
                'selling_price' => 2600,
                'current_stock' => 17,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0083',
                'name' => 'AC Condenser',
                'category' => 'AC & HVAC',
                'brand' => 'Valeo',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 20,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0084',
                'name' => 'AC Evaporator',
                'category' => 'AC & HVAC',
                'brand' => 'Denso',
                'unit' => 'pcs',
                'cost_price' => 1800,
                'selling_price' => 2600,
                'current_stock' => 23,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0085',
                'name' => 'AC Expansion Valve',
                'category' => 'AC & HVAC',
                'brand' => 'SKF',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 26,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0086',
                'name' => 'AC Receiver Drier',
                'category' => 'AC & HVAC',
                'brand' => 'NGK',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 29,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0087',
                'name' => 'AC Pressure Switch',
                'category' => 'AC & HVAC',
                'brand' => 'Exide',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 6,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0088',
                'name' => 'AC Blower Motor',
                'category' => 'AC & HVAC',
                'brand' => 'Amaron',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 9,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0089',
                'name' => 'Blower Resistor',
                'category' => 'AC & HVAC',
                'brand' => 'Gates',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 12,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0090',
                'name' => 'AC Belt',
                'category' => 'AC & HVAC',
                'brand' => 'Generic',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 15,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0091',
                'name' => 'AC O-Ring Kit',
                'category' => 'AC & HVAC',
                'brand' => 'Bosch',
                'unit' => 'set',
                'cost_price' => 450,
                'selling_price' => 650,
                'current_stock' => 18,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0092',
                'name' => 'AC Refrigerant Gas Can',
                'category' => 'AC & HVAC',
                'brand' => 'MANN',
                'unit' => 'bottle',
                'cost_price' => 250,
                'selling_price' => 380,
                'current_stock' => 21,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0093',
                'name' => 'Battery 35Ah',
                'category' => 'Electrical',
                'brand' => 'Valeo',
                'unit' => 'pcs',
                'cost_price' => 3200,
                'selling_price' => 4200,
                'current_stock' => 24,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0094',
                'name' => 'Battery 45Ah',
                'category' => 'Electrical',
                'brand' => 'Denso',
                'unit' => 'pcs',
                'cost_price' => 3200,
                'selling_price' => 4200,
                'current_stock' => 27,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0095',
                'name' => 'Battery 60Ah',
                'category' => 'Electrical',
                'brand' => 'SKF',
                'unit' => 'pcs',
                'cost_price' => 3200,
                'selling_price' => 4200,
                'current_stock' => 30,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0096',
                'name' => 'Alternator Belt',
                'category' => 'Electrical',
                'brand' => 'NGK',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 7,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0097',
                'name' => 'Starter Motor',
                'category' => 'Electrical',
                'brand' => 'Exide',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 10,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0098',
                'name' => 'Alternator Assembly',
                'category' => 'Electrical',
                'brand' => 'Amaron',
                'unit' => 'pcs',
                'cost_price' => 1800,
                'selling_price' => 2600,
                'current_stock' => 13,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0099',
                'name' => 'Fuse Mini Pack',
                'category' => 'Electrical',
                'brand' => 'Gates',
                'unit' => 'set',
                'cost_price' => 450,
                'selling_price' => 650,
                'current_stock' => 16,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0100',
                'name' => 'Relay 12V',
                'category' => 'Electrical',
                'brand' => 'Generic',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 19,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0101',
                'name' => 'Horn Pair',
                'category' => 'Electrical',
                'brand' => 'Bosch',
                'unit' => 'set',
                'cost_price' => 450,
                'selling_price' => 650,
                'current_stock' => 22,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0102',
                'name' => 'Headlight Bulb H4',
                'category' => 'Electrical',
                'brand' => 'MANN',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 25,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0103',
                'name' => 'Headlight Bulb H7',
                'category' => 'Electrical',
                'brand' => 'Valeo',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 28,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0104',
                'name' => 'Indicator Bulb',
                'category' => 'Electrical',
                'brand' => 'Denso',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 5,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0105',
                'name' => 'Tail Light Bulb',
                'category' => 'Electrical',
                'brand' => 'SKF',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 8,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0106',
                'name' => 'Wiper Motor',
                'category' => 'Electrical',
                'brand' => 'NGK',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 11,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0107',
                'name' => 'Wiper Blade Pair',
                'category' => 'Electrical',
                'brand' => 'Exide',
                'unit' => 'set',
                'cost_price' => 450,
                'selling_price' => 650,
                'current_stock' => 14,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0108',
                'name' => 'Battery Terminal Pair',
                'category' => 'Electrical',
                'brand' => 'Amaron',
                'unit' => 'pcs',
                'cost_price' => 3200,
                'selling_price' => 4200,
                'current_stock' => 17,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0109',
                'name' => 'Ignition Coil',
                'category' => 'Electrical',
                'brand' => 'Gates',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 20,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0110',
                'name' => 'Crankshaft Position Sensor',
                'category' => 'Electrical',
                'brand' => 'Generic',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 23,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0111',
                'name' => 'Camshaft Position Sensor',
                'category' => 'Electrical',
                'brand' => 'Bosch',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 26,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0112',
                'name' => 'Oxygen Sensor',
                'category' => 'Electrical',
                'brand' => 'MANN',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 29,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0113',
                'name' => 'Front Bumper',
                'category' => 'Body & Exterior',
                'brand' => 'Valeo',
                'unit' => 'pcs',
                'cost_price' => 1800,
                'selling_price' => 2600,
                'current_stock' => 6,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0114',
                'name' => 'Rear Bumper',
                'category' => 'Body & Exterior',
                'brand' => 'Denso',
                'unit' => 'pcs',
                'cost_price' => 1800,
                'selling_price' => 2600,
                'current_stock' => 9,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0115',
                'name' => 'Fender Front Left',
                'category' => 'Body & Exterior',
                'brand' => 'SKF',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 12,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0116',
                'name' => 'Fender Front Right',
                'category' => 'Body & Exterior',
                'brand' => 'NGK',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 15,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0117',
                'name' => 'Bonnet',
                'category' => 'Body & Exterior',
                'brand' => 'Exide',
                'unit' => 'pcs',
                'cost_price' => 1800,
                'selling_price' => 2600,
                'current_stock' => 18,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0118',
                'name' => 'Door Mirror Left',
                'category' => 'Body & Exterior',
                'brand' => 'Amaron',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 21,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0119',
                'name' => 'Door Mirror Right',
                'category' => 'Body & Exterior',
                'brand' => 'Gates',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 24,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0120',
                'name' => 'Door Handle Exterior',
                'category' => 'Body & Exterior',
                'brand' => 'Generic',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 27,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0121',
                'name' => 'Front Grille',
                'category' => 'Body & Exterior',
                'brand' => 'Bosch',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 30,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0122',
                'name' => 'Bumper Bracket',
                'category' => 'Body & Exterior',
                'brand' => 'MANN',
                'unit' => 'pcs',
                'cost_price' => 1800,
                'selling_price' => 2600,
                'current_stock' => 7,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0123',
                'name' => 'Mud Flap Set',
                'category' => 'Body & Exterior',
                'brand' => 'Valeo',
                'unit' => 'set',
                'cost_price' => 450,
                'selling_price' => 650,
                'current_stock' => 10,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0124',
                'name' => 'Number Plate Frame',
                'category' => 'Body & Exterior',
                'brand' => 'Denso',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 13,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0125',
                'name' => 'Door Beading',
                'category' => 'Body & Exterior',
                'brand' => 'SKF',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 16,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0126',
                'name' => 'Windshield Glass',
                'category' => 'Body & Exterior',
                'brand' => 'NGK',
                'unit' => 'pcs',
                'cost_price' => 1800,
                'selling_price' => 2600,
                'current_stock' => 19,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0127',
                'name' => 'Rear Windshield Glass',
                'category' => 'Body & Exterior',
                'brand' => 'Exide',
                'unit' => 'pcs',
                'cost_price' => 1800,
                'selling_price' => 2600,
                'current_stock' => 22,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0128',
                'name' => 'Side Window Glass',
                'category' => 'Body & Exterior',
                'brand' => 'Amaron',
                'unit' => 'pcs',
                'cost_price' => 1800,
                'selling_price' => 2600,
                'current_stock' => 25,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0129',
                'name' => 'Headlamp Left',
                'category' => 'Lighting',
                'brand' => 'Gates',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 28,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0130',
                'name' => 'Headlamp Right',
                'category' => 'Lighting',
                'brand' => 'Generic',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 5,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0131',
                'name' => 'Tail Lamp Left',
                'category' => 'Lighting',
                'brand' => 'Bosch',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 8,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0132',
                'name' => 'Tail Lamp Right',
                'category' => 'Lighting',
                'brand' => 'MANN',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 11,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0133',
                'name' => 'Fog Lamp Pair',
                'category' => 'Lighting',
                'brand' => 'Valeo',
                'unit' => 'set',
                'cost_price' => 450,
                'selling_price' => 650,
                'current_stock' => 14,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0134',
                'name' => 'Daytime Running Lamp',
                'category' => 'Lighting',
                'brand' => 'Denso',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 17,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0135',
                'name' => 'Indicator Assembly Left',
                'category' => 'Lighting',
                'brand' => 'SKF',
                'unit' => 'pcs',
                'cost_price' => 1800,
                'selling_price' => 2600,
                'current_stock' => 20,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0136',
                'name' => 'Indicator Assembly Right',
                'category' => 'Lighting',
                'brand' => 'NGK',
                'unit' => 'pcs',
                'cost_price' => 1800,
                'selling_price' => 2600,
                'current_stock' => 23,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0137',
                'name' => 'Interior Roof Lamp',
                'category' => 'Lighting',
                'brand' => 'Exide',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 26,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0138',
                'name' => 'Number Plate Lamp',
                'category' => 'Lighting',
                'brand' => 'Amaron',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 29,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0139',
                'name' => 'Cabin Floor Mat Set',
                'category' => 'Interior',
                'brand' => 'Gates',
                'unit' => 'set',
                'cost_price' => 450,
                'selling_price' => 650,
                'current_stock' => 6,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0140',
                'name' => 'Boot Mat',
                'category' => 'Interior',
                'brand' => 'Generic',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 9,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0141',
                'name' => 'Seat Cover Set',
                'category' => 'Interior',
                'brand' => 'Bosch',
                'unit' => 'set',
                'cost_price' => 450,
                'selling_price' => 650,
                'current_stock' => 12,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0142',
                'name' => 'Dashboard Polish',
                'category' => 'Interior',
                'brand' => 'MANN',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 15,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0143',
                'name' => 'Interior Cleaner',
                'category' => 'Interior',
                'brand' => 'Valeo',
                'unit' => 'bottle',
                'cost_price' => 250,
                'selling_price' => 380,
                'current_stock' => 18,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0144',
                'name' => 'Door Trim Clip Pack',
                'category' => 'Interior',
                'brand' => 'Denso',
                'unit' => 'set',
                'cost_price' => 450,
                'selling_price' => 650,
                'current_stock' => 21,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0145',
                'name' => 'Dashboard Clip Pack',
                'category' => 'Interior',
                'brand' => 'SKF',
                'unit' => 'set',
                'cost_price' => 450,
                'selling_price' => 650,
                'current_stock' => 24,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0146',
                'name' => 'Sun Visor',
                'category' => 'Interior',
                'brand' => 'NGK',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 27,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0147',
                'name' => 'Door Lock Actuator',
                'category' => 'Interior',
                'brand' => 'Exide',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 30,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0148',
                'name' => 'Power Window Switch',
                'category' => 'Interior',
                'brand' => 'Amaron',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 7,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0149',
                'name' => 'Window Regulator',
                'category' => 'Interior',
                'brand' => 'Gates',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 10,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0150',
                'name' => 'Central Locking Actuator',
                'category' => 'Interior',
                'brand' => 'Generic',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 13,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0151',
                'name' => 'Tyre 175/65 R15',
                'category' => 'Tyres & Wheels',
                'brand' => 'Bosch',
                'unit' => 'pcs',
                'cost_price' => 2800,
                'selling_price' => 3600,
                'current_stock' => 16,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0152',
                'name' => 'Tyre 185/65 R15',
                'category' => 'Tyres & Wheels',
                'brand' => 'MANN',
                'unit' => 'pcs',
                'cost_price' => 2800,
                'selling_price' => 3600,
                'current_stock' => 19,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0153',
                'name' => 'Tyre 195/55 R16',
                'category' => 'Tyres & Wheels',
                'brand' => 'Valeo',
                'unit' => 'pcs',
                'cost_price' => 2800,
                'selling_price' => 3600,
                'current_stock' => 22,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0154',
                'name' => 'Tyre 205/55 R16',
                'category' => 'Tyres & Wheels',
                'brand' => 'Denso',
                'unit' => 'pcs',
                'cost_price' => 2800,
                'selling_price' => 3600,
                'current_stock' => 25,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0155',
                'name' => 'Wheel Alignment Weight Pack',
                'category' => 'Tyres & Wheels',
                'brand' => 'SKF',
                'unit' => 'set',
                'cost_price' => 450,
                'selling_price' => 650,
                'current_stock' => 28,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0156',
                'name' => 'Tyre Valve',
                'category' => 'Tyres & Wheels',
                'brand' => 'NGK',
                'unit' => 'pcs',
                'cost_price' => 2800,
                'selling_price' => 3600,
                'current_stock' => 5,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0157',
                'name' => 'Puncture Repair Strip Pack',
                'category' => 'Tyres & Wheels',
                'brand' => 'Exide',
                'unit' => 'set',
                'cost_price' => 450,
                'selling_price' => 650,
                'current_stock' => 8,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0158',
                'name' => 'Wheel Nut Set',
                'category' => 'Tyres & Wheels',
                'brand' => 'Amaron',
                'unit' => 'set',
                'cost_price' => 450,
                'selling_price' => 650,
                'current_stock' => 11,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0159',
                'name' => 'Wheel Cap Set',
                'category' => 'Tyres & Wheels',
                'brand' => 'Gates',
                'unit' => 'set',
                'cost_price' => 450,
                'selling_price' => 650,
                'current_stock' => 14,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0160',
                'name' => 'Tyre Inflator Hose',
                'category' => 'Tyres & Wheels',
                'brand' => 'Generic',
                'unit' => 'pcs',
                'cost_price' => 2800,
                'selling_price' => 3600,
                'current_stock' => 17,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0161',
                'name' => 'Oil Filter Small',
                'category' => 'Filters',
                'brand' => 'Bosch',
                'unit' => 'bottle',
                'cost_price' => 250,
                'selling_price' => 380,
                'current_stock' => 20,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0162',
                'name' => 'Oil Filter Large',
                'category' => 'Filters',
                'brand' => 'MANN',
                'unit' => 'bottle',
                'cost_price' => 250,
                'selling_price' => 380,
                'current_stock' => 23,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0163',
                'name' => 'Air Filter Hatchback',
                'category' => 'Filters',
                'brand' => 'Valeo',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 26,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0164',
                'name' => 'Air Filter Sedan',
                'category' => 'Filters',
                'brand' => 'Denso',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 29,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0165',
                'name' => 'Cabin Filter Standard',
                'category' => 'Filters',
                'brand' => 'SKF',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 6,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0166',
                'name' => 'Cabin Filter Carbon',
                'category' => 'Filters',
                'brand' => 'NGK',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 9,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0167',
                'name' => 'Fuel Filter Petrol',
                'category' => 'Filters',
                'brand' => 'Exide',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 12,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0168',
                'name' => 'Fuel Filter Diesel',
                'category' => 'Filters',
                'brand' => 'Amaron',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 15,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0169',
                'name' => 'Microfiber Cloth Pack',
                'category' => 'Consumables & Workshop',
                'brand' => 'Gates',
                'unit' => 'set',
                'cost_price' => 450,
                'selling_price' => 650,
                'current_stock' => 18,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0170',
                'name' => 'Masking Tape',
                'category' => 'Consumables & Workshop',
                'brand' => 'Generic',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 21,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0171',
                'name' => 'Insulation Tape',
                'category' => 'Consumables & Workshop',
                'brand' => 'Bosch',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 24,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0172',
                'name' => 'Cable Tie Pack',
                'category' => 'Consumables & Workshop',
                'brand' => 'MANN',
                'unit' => 'set',
                'cost_price' => 450,
                'selling_price' => 650,
                'current_stock' => 27,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0173',
                'name' => 'Sandpaper Pack',
                'category' => 'Consumables & Workshop',
                'brand' => 'Valeo',
                'unit' => 'set',
                'cost_price' => 450,
                'selling_price' => 650,
                'current_stock' => 30,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0174',
                'name' => 'Silicone Sealant',
                'category' => 'Consumables & Workshop',
                'brand' => 'Denso',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 7,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0175',
                'name' => 'Thread Locker',
                'category' => 'Consumables & Workshop',
                'brand' => 'SKF',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 10,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0176',
                'name' => 'Contact Cleaner',
                'category' => 'Consumables & Workshop',
                'brand' => 'NGK',
                'unit' => 'bottle',
                'cost_price' => 250,
                'selling_price' => 380,
                'current_stock' => 13,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0177',
                'name' => 'Rust Penetrant Spray',
                'category' => 'Consumables & Workshop',
                'brand' => 'Exide',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 16,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0178',
                'name' => 'Brake Grease',
                'category' => 'Consumables & Workshop',
                'brand' => 'Amaron',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 19,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0179',
                'name' => 'Cutting Compound',
                'category' => 'Consumables & Workshop',
                'brand' => 'Gates',
                'unit' => 'bottle',
                'cost_price' => 250,
                'selling_price' => 380,
                'current_stock' => 22,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0180',
                'name' => 'Rubbing Compound',
                'category' => 'Consumables & Workshop',
                'brand' => 'Generic',
                'unit' => 'bottle',
                'cost_price' => 250,
                'selling_price' => 380,
                'current_stock' => 25,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0181',
                'name' => 'Car Shampoo 1L',
                'category' => 'Consumables & Workshop',
                'brand' => 'Bosch',
                'unit' => 'bottle',
                'cost_price' => 250,
                'selling_price' => 380,
                'current_stock' => 28,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0182',
                'name' => 'Glass Cleaner 500ml',
                'category' => 'Consumables & Workshop',
                'brand' => 'MANN',
                'unit' => 'pcs',
                'cost_price' => 1800,
                'selling_price' => 2600,
                'current_stock' => 5,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0183',
                'name' => 'Plastic Trim Restorer',
                'category' => 'Consumables & Workshop',
                'brand' => 'Valeo',
                'unit' => 'pcs',
                'cost_price' => 350,
                'selling_price' => 550,
                'current_stock' => 8,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0184',
                'name' => 'Disposable Gloves Pack',
                'category' => 'Consumables & Workshop',
                'brand' => 'Denso',
                'unit' => 'set',
                'cost_price' => 450,
                'selling_price' => 650,
                'current_stock' => 11,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0185',
                'name' => 'Nitrile Gloves Pack',
                'category' => 'Consumables & Workshop',
                'brand' => 'SKF',
                'unit' => 'set',
                'cost_price' => 450,
                'selling_price' => 650,
                'current_stock' => 14,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0186',
                'name' => 'Shop Wipes Pack',
                'category' => 'Consumables & Workshop',
                'brand' => 'NGK',
                'unit' => 'set',
                'cost_price' => 450,
                'selling_price' => 650,
                'current_stock' => 17,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0187',
                'name' => 'Periodic Service Kit Small Car',
                'category' => 'Service Kits',
                'brand' => 'Exide',
                'unit' => 'set',
                'cost_price' => 450,
                'selling_price' => 650,
                'current_stock' => 20,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0188',
                'name' => 'Periodic Service Kit Sedan',
                'category' => 'Service Kits',
                'brand' => 'Amaron',
                'unit' => 'set',
                'cost_price' => 450,
                'selling_price' => 650,
                'current_stock' => 23,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0189',
                'name' => 'Periodic Service Kit SUV',
                'category' => 'Service Kits',
                'brand' => 'Gates',
                'unit' => 'set',
                'cost_price' => 450,
                'selling_price' => 650,
                'current_stock' => 26,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0190',
                'name' => 'Oil Change Kit Petrol',
                'category' => 'Service Kits',
                'brand' => 'Generic',
                'unit' => 'bottle',
                'cost_price' => 250,
                'selling_price' => 380,
                'current_stock' => 29,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0191',
                'name' => 'Oil Change Kit Diesel',
                'category' => 'Service Kits',
                'brand' => 'Bosch',
                'unit' => 'bottle',
                'cost_price' => 250,
                'selling_price' => 380,
                'current_stock' => 6,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0192',
                'name' => 'AC Service Kit',
                'category' => 'Service Kits',
                'brand' => 'MANN',
                'unit' => 'set',
                'cost_price' => 450,
                'selling_price' => 650,
                'current_stock' => 9,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0193',
                'name' => 'Brake Service Kit Front',
                'category' => 'Service Kits',
                'brand' => 'Valeo',
                'unit' => 'set',
                'cost_price' => 450,
                'selling_price' => 650,
                'current_stock' => 12,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0194',
                'name' => 'Brake Service Kit Rear',
                'category' => 'Service Kits',
                'brand' => 'Denso',
                'unit' => 'set',
                'cost_price' => 450,
                'selling_price' => 650,
                'current_stock' => 15,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
            [
                'part_number' => 'DEMO-0195',
                'name' => 'Cooling System Service Kit',
                'category' => 'Service Kits',
                'brand' => 'SKF',
                'unit' => 'set',
                'cost_price' => 450,
                'selling_price' => 650,
                'current_stock' => 18,
                'minimum_stock' => 5,
                'is_active' => true,
            ],
        ];

        foreach ($parts as $part) {
            Part::updateOrCreate(
                ['part_number' => $part['part_number']],
                $part
            );
        }
    }
}
